version: "3.7"

services:
  postgres_db:
    image: postgres
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 5432:5432

  mongo_db:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017

  api:
    build: ./api-gateway/
    environment:
      PORT: 3330
    ports:
      - 3330:3330

  auth:
    build: ./auth/
    environment:
      PORT: 3331
    ports:
      - 3331:3331
    depends_on:
      - mongo_db
    links:
      - mongo_db

  profiles:
    build: ./profiles/
    environment:
      PORT: 3332
    ports:
      - 3332:3332
    depends_on:
      - mongo_db
    links:
      - mongo_db

  course:
    build: ./courses/
    env_file:
      - ./courses/.env
    command:
      - yarn sequelize db:migrate
      - yarn start
    environment:
      PORT: 3333
    ports:
      - 3333:3333
    depends_on:
      - postgres_db
    links:
      - postgres_db
